export {h} from './h'
export {renderSlots} from './helper/renderSlots'
export {createTextVNode} from './vnode'
export {getCurrentInstance} from './component'
export{provide,inject} from './apiProvideInject'
export{createRender} from './render'